version: "3.8"

services:
  db:
    image: mysql:8.2.0
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: appdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_SSL_MODE: ${DATABASE_SSL_MODE}
      CLIENT_BASE_URL: ${CLIENT_BASE_URL}

volumes:
  mysql_data:
